# Generated by Django 4.0.6 on 2022-07-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', null=True, upload_to=''),
        ),
    ]
