# Generated by Django 4.0.6 on 2022-07-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpack',
            name='pack_type',
            field=models.CharField(choices=[('KG', 'KG'), ('LTR', 'LTR')], default='KG', max_length=10),
        ),
    ]
