# Generated by Django 4.0.6 on 2022-07-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_productpack_pack_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpack',
            name='pack_type',
            field=models.CharField(choices=[('KG', 'KG'), ('LTR', 'LTR')], default='LTR', max_length=10),
        ),
    ]
